### ISSUE TITLE
New pre-trained model

### ISSUE THREAD

**Issue by pourfard** [ShawnNew/AMSMNet#35]
Hi,
When I run test.py I get this error:
`copying a param with shape torch.Size([64, 128, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
`
I think, pre-trained model is for previous version. Can you please update the `pretrained.pth` file? I didn't change any param in the config file.

complete error code:

```
Trainable parameters: 5759030
Traceback (most recent call last):
  File "/home/mahdi/Temp/Mask/AMSMNet/test.py", line 183, in <module>
    main(config, args.resume, args.device, output_path)
  File "/home/mahdi/Temp/Mask/AMSMNet/test.py", line 113, in main
    model.load_state_dict(state_dict)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DataParallel:
	Missing key(s) in state_dict: "module.msmnet_model.body.2.weight", "module.msmnet_model.body.2.bias". 
	Unexpected key(s) in state_dict: "module.msmnet_model.body.3.body.0.weight", "module.msmnet_model.body.3.body.0.bias", "module.msmnet_model.body.3.body.1.weight", "module.msmnet_model.body.3.body.1.bias", "module.msmnet_model.body.3.body.1.running_mean", "module.msmnet_model.body.3.body.1.running_var", "module.msmnet_model.body.3.body.1.num_batches_tracked", "module.msmnet_model.body.3.body.3.weight", "module.msmnet_model.body.3.body.3.bias", "module.msmnet_model.body.3.body.4.weight", "module.msmnet_model.body.3.body.4.bias", "module.msmnet_model.body.3.body.4.running_mean", "module.msmnet_model.body.3.body.4.running_var", "module.msmnet_model.body.3.body.4.num_batches_tracked", "module.msmnet_model.body.4.body.0.weight", "module.msmnet_model.body.4.body.0.bias", "module.msmnet_model.body.4.body.1.weight", "module.msmnet_model.body.4.body.1.bias", "module.msmnet_model.body.4.body.1.running_mean", "module.msmnet_model.body.4.body.1.running_var", "module.msmnet_model.body.4.body.1.num_batches_tracked", "module.msmnet_model.body.4.body.3.weight", "module.msmnet_model.body.4.body.3.bias", "module.msmnet_model.body.4.body.4.weight", "module.msmnet_model.body.4.body.4.bias", "module.msmnet_model.body.4.body.4.running_mean", "module.msmnet_model.body.4.body.4.running_var", "module.msmnet_model.body.4.body.4.num_batches_tracked", "module.msmnet_model.body.5.body.0.weight", "module.msmnet_model.body.5.body.0.bias", "module.msmnet_model.body.5.body.1.weight", "module.msmnet_model.body.5.body.1.bias", "module.msmnet_model.body.5.body.1.running_mean", "module.msmnet_model.body.5.body.1.running_var", "module.msmnet_model.body.5.body.1.num_batches_tracked", "module.msmnet_model.body.5.body.3.weight", "module.msmnet_model.body.5.body.3.bias", "module.msmnet_model.body.5.body.4.weight", "module.msmnet_model.body.5.body.4.bias", "module.msmnet_model.body.5.body.4.running_mean", "module.msmnet_model.body.5.body.4.running_var", "module.msmnet_model.body.5.body.4.num_batches_tracked", "module.msmnet_model.body.6.weight", "module.msmnet_model.body.6.bias", "module.msmnet_model.body.2.body.0.weight", "module.msmnet_model.body.2.body.0.bias", "module.msmnet_model.body.2.body.1.weight", "module.msmnet_model.body.2.body.1.bias", "module.msmnet_model.body.2.body.1.running_mean", "module.msmnet_model.body.2.body.1.running_var", "module.msmnet_model.body.2.body.1.num_batches_tracked", "module.msmnet_model.body.2.body.3.weight", "module.msmnet_model.body.2.body.3.bias", "module.msmnet_model.body.2.body.4.weight", "module.msmnet_model.body.2.body.4.bias", "module.msmnet_model.body.2.body.4.running_mean", "module.msmnet_model.body.2.body.4.running_var", "module.msmnet_model.body.2.body.4.num_batches_tracked", "module.fusion_model.fusion_model.1.2.body.0.weight", "module.fusion_model.fusion_model.1.2.body.0.bias", "module.fusion_model.fusion_model.1.2.body.1.weight", "module.fusion_model.fusion_model.1.2.body.1.bias", "module.fusion_model.fusion_model.1.2.body.1.running_mean", "module.fusion_model.fusion_model.1.2.body.1.running_var", "module.fusion_model.fusion_model.1.2.body.1.num_batches_tracked", "module.fusion_model.fusion_model.1.2.body.3.weight", "module.fusion_model.fusion_model.1.2.body.3.bias", "module.fusion_model.fusion_model.1.2.body.4.weight", "module.fusion_model.fusion_model.1.2.body.4.bias", "module.fusion_model.fusion_model.1.2.body.4.running_mean", "module.fusion_model.fusion_model.1.2.body.4.running_var", "module.fusion_model.fusion_model.1.2.body.4.num_batches_tracked", "module.fusion_model.fusion_model.1.3.body.0.weight", "module.fusion_model.fusion_model.1.3.body.0.bias", "module.fusion_model.fusion_model.1.3.body.1.weight", "module.fusion_model.fusion_model.1.3.body.1.bias", "module.fusion_model.fusion_model.1.3.body.1.running_mean", "module.fusion_model.fusion_model.1.3.body.1.running_var", "module.fusion_model.fusion_model.1.3.body.1.num_batches_tracked", "module.fusion_model.fusion_model.1.3.body.3.weight", "module.fusion_model.fusion_model.1.3.body.3.bias", "module.fusion_model.fusion_model.1.3.body.4.weight", "module.fusion_model.fusion_model.1.3.body.4.bias", "module.fusion_model.fusion_model.1.3.body.4.running_mean", "module.fusion_model.fusion_model.1.3.body.4.running_var", "module.fusion_model.fusion_model.1.3.body.4.num_batches_tracked", "module.fusion_model.fusion_model.1.4.body.0.weight", "module.fusion_model.fusion_model.1.4.body.0.bias", "module.fusion_model.fusion_model.1.4.body.1.weight", "module.fusion_model.fusion_model.1.4.body.1.bias", "module.fusion_model.fusion_model.1.4.body.1.running_mean", "module.fusion_model.fusion_model.1.4.body.1.running_var", "module.fusion_model.fusion_model.1.4.body.1.num_batches_tracked", "module.fusion_model.fusion_model.1.4.body.3.weight", "module.fusion_model.fusion_model.1.4.body.3.bias", "module.fusion_model.fusion_model.1.4.body.4.weight", "module.fusion_model.fusion_model.1.4.body.4.bias", "module.fusion_model.fusion_model.1.4.body.4.running_mean", "module.fusion_model.fusion_model.1.4.body.4.running_var", "module.fusion_model.fusion_model.1.4.body.4.num_batches_tracked", "module.fusion_model.fusion_model.1.5.body.0.weight", "module.fusion_model.fusion_model.1.5.body.0.bias", "module.fusion_model.fusion_model.1.5.body.1.weight", "module.fusion_model.fusion_model.1.5.body.1.bias", "module.fusion_model.fusion_model.1.5.body.1.running_mean", "module.fusion_model.fusion_model.1.5.body.1.running_var", "module.fusion_model.fusion_model.1.5.body.1.num_batches_tracked", "module.fusion_model.fusion_model.1.5.body.3.weight", "module.fusion_model.fusion_model.1.5.body.3.bias", "module.fusion_model.fusion_model.1.5.body.4.weight", "module.fusion_model.fusion_model.1.5.body.4.bias", "module.fusion_model.fusion_model.1.5.body.4.running_mean", "module.fusion_model.fusion_model.1.5.body.4.running_var", "module.fusion_model.fusion_model.1.5.body.4.num_batches_tracked". 
	size mismatch for module.fusion_model.fusion_model.0.0.weight: copying a param with shape torch.Size([64, 128, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
```

**Comment by vallegro** [comment]
Hi, @pourfard , I met the same issue. How did you solved this? Thx

**Comment by vallegro** [comment]
turing off DataParallel unbolcked me heree
